"""The demo pages must be what the agents actually write.

A page committed once and never regenerated is a screenshot with an `.html` extension. It goes stale
the first time an agent changes and nothing notices — which is the same failure as a README stating
a number nobody re-measures, and this repository has shipped that twice.

So the pages are generated by `examples/demo/build.py`, and this regenerates them and compares.
"""
import importlib.util
import re
from pathlib import Path

import pytest

DEMO = Path(__file__).resolve().parent.parent / "examples" / "demo"
EXAMPLES = DEMO.parent


def _builder():
    spec = importlib.util.spec_from_file_location("demo_build", DEMO / "build.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


build = _builder()
GENERATED = build.generate()


@pytest.mark.parametrize("name", sorted(GENERATED))
def test_the_committed_page_is_the_one_the_agent_writes_today(name):
    on_disk = (DEMO / name)
    assert on_disk.exists(), f"{name} is missing; run `python3 examples/demo/build.py`"
    assert on_disk.read_text(encoding="utf-8") == GENERATED[name], (
        f"{name} is stale — the agent that builds it has changed. "
        f"Run `python3 examples/demo/build.py`.")


@pytest.mark.parametrize("demo", build.DEMOS, ids=lambda d: d["slug"])
def test_each_page_is_self_contained(demo):
    """A demo you cannot open by double-clicking is not much of a demo. The only thing any of them
    may reach for is a font."""
    page = GENERATED[f'{demo["slug"]}.html']
    assert 'href="styles.css"' not in page and "<script src=" not in page
    for reaching in ("fetch(", "XMLHttpRequest", "EventSource", "cdn.", "unpkg", "jsdelivr"):
        assert reaching not in page, f'{demo["slug"]}.html reaches for {reaching}'
    external = set(re.findall(r"https?://[^\s\"'<>)]+", page))
    allowed = {u for u in external if u.startswith("https://fonts.")}
    assert external == allowed, f"{demo['slug']}.html reaches off-machine: {external - allowed}"


@pytest.mark.parametrize("demo", build.DEMOS, ids=lambda d: d["slug"])
def test_the_index_links_every_demo_it_lists(demo):
    index = GENERATED["index.html"]
    assert f'href="{demo["slug"]}.html"' in index
    assert demo["title"] in index


def test_the_index_links_every_example_readme():
    index = GENERATED["index.html"]
    for example in ("minimal", "tide-spa", "weather-spa"):
        assert f"../{example}/README.md" in index, f"{example} is not linked from the demo index"


def test_every_example_has_its_own_readme():
    """Each example stands on its own. `examples/README.md` is the way in, not the documentation."""
    for example in ("minimal", "tide-spa", "weather-spa"):
        readme = EXAMPLES / example / "README.md"
        assert readme.exists(), f"{example} has no README of its own"
        assert readme.read_text(encoding="utf-8").lstrip().startswith("#")


def test_the_examples_index_links_each_one():
    index = (EXAMPLES / "README.md").read_text(encoding="utf-8")
    for example in ("minimal", "tide-spa", "weather-spa"):
        assert f"{example}/README.md" in index, f"{example} is not linked from examples/README.md"


def test_the_main_readme_links_the_examples_index_and_each_readme():
    main = (EXAMPLES.parent / "README.md").read_text(encoding="utf-8")
    assert "examples/README.md" in main
    for example in ("minimal", "tide-spa", "weather-spa"):
        assert f"examples/{example}/README.md" in main, f"the main README does not link {example}"


def test_every_relative_link_in_an_example_readme_resolves():
    """A README full of links that 404 is worse than one with none — it claims a structure that is
    not there. Anchors and external URLs are skipped; the point is the files."""
    broken = []
    for readme in sorted(EXAMPLES.rglob("README.md")):
        for target in re.findall(r"\]\(([^)]+)\)", readme.read_text(encoding="utf-8")):
            if target.startswith(("http://", "https://", "#", "mailto:")):
                continue
            path = (readme.parent / target.split("#", 1)[0]).resolve()
            if not path.exists():
                broken.append(f"{readme.relative_to(EXAMPLES.parent)} -> {target}")
    assert not broken, "dead links: " + ", ".join(broken)


def test_the_agents_the_demos_use_do_not_pick_the_next_module_by_missing_file(tmp_path):
    """The bug `weather-spa` scenario C exists to show. An agent with it cannot finish a rebuild, so
    `build.py` cannot generate a page from it — this asserts the shipped agents are the fixed kind
    by driving each one past the point where the broken kind loops."""
    import json
    import subprocess
    import sys

    for demo in build.DEMOS:
        work = tmp_path / demo["example"]
        work.mkdir(parents=True)
        (work / "agent.py").write_text(
            (EXAMPLES / demo["example"] / "agent.py").read_text(encoding="utf-8"),
            encoding="utf-8")
        order = json.dumps({"node_id": "engineer_build", "seat": None})
        answers = []
        for _ in range(6):
            done = subprocess.run([sys.executable, str(work / "agent.py")], input=order,
                                  capture_output=True, encoding="utf-8", errors="replace",
                                  cwd=str(work))
            answers.append(json.loads(done.stdout)["module"])
        assert answers[4] == "", (
            f'{demo["example"]}: a fifth build answered {answers[4]!r} instead of reporting '
            f"nothing to do — the frontier would never empty")


# ── the recording demo ────────────────────────────────────────────────────────────────────────

def test_the_recording_is_rendered_by_the_shipped_exporter():
    """Not by anything local to `examples/demo/`. The page is a demonstration **of the feature**, so
    if `--format playback` breaks, this page must break with it rather than keep working from a
    private copy of the renderer."""
    import ast

    source = (DEMO / "build.py").read_text(encoding="utf-8")
    tree = ast.parse(source)
    calls = [n for n in ast.walk(tree) if isinstance(n, ast.Call)
             and ast.unparse(n.func).endswith("export_conversation")]
    assert calls, "the recording page must go through conversations.export_conversation"
    assert any(ast.unparse(a) == "'playback'" or ast.unparse(a) == '"playback"'
               for call in calls for a in call.args), "it must ask for the playback format"


def test_the_recording_replays_a_real_console_driven_run():
    """The point of the fixture: it holds what a person typed and what a person decided. A CLI run
    has neither, and a recording of one shows only the model's half.

    Asserted against the conversation, not against the rendered payload: the page's field names are
    the exporter's business and a test that pinned them would fail on a rename that changed nothing.
    What must hold is that the *run* has both operator kinds in it.
    """
    from ai_sdlc_runner import conversations as conv

    back = conv.backend("file", root=DEMO / "conversations")
    entry = back.conversations()[0]
    document = conv.Conversation(back, entry["project"]["name"],
                                 conversation_id=entry["conversation_id"]).document()
    kinds = {t["kind"] for t in document["turns"]}
    assert conv.INSTRUCTION in kinds, "no instruction turn; this was not typed by a person"
    assert conv.DECISION in kinds, "no decision turn; no gate was approved by a person"
    assert sum(t["kind"] == conv.INSTRUCTION for t in document["turns"]) == 2, (
        "the fixture should carry both instructions — the brief and the follow-up")

    page = GENERATED["recording.html"]
    assert '"who": "operator"' in page or '"who":"operator"' in page, (
        "the page does not mark the operator's turns apart")


def test_no_absolute_path_from_the_machine_that_recorded_it_survives():
    """The `opened` turn records the journal directory the run happened in. Nobody needs a
    stranger's temp path in their repository, so `make_fixture.py` scrubs it — and this is what
    stops a refreshed fixture from quietly reintroducing one."""
    import re

    for path in sorted((DEMO / "conversations").rglob("*")):
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8")
        found = re.findall(r'[A-Za-z]:\\[^"]*|/(?:home|Users|tmp)/[^"]*', text)
        assert not found, f"{path.name} still names a real path: {found[0][:90]}"
    assert "<journal>" in (DEMO / "conversations").rglob("*.jsonl").__next__().read_text(
        encoding="utf-8"), "the placeholder is missing; scrubbing may have stopped running"


def test_the_fixture_holds_exactly_one_conversation():
    """`build.py` refuses otherwise rather than picking one. Two conversations in the fixture would
    make the demo page depend on directory ordering."""
    from ai_sdlc_runner import conversations as conv

    listed = conv.backend("file", root=DEMO / "conversations").conversations()
    assert len(listed) == 1, f"the fixture holds {len(listed)} conversations"


def test_the_recording_is_linked_from_the_index():
    index = GENERATED["index.html"]
    assert 'href="recording.html"' in index
    assert build.RECORDING["title"] in index


def test_the_fixture_is_not_so_large_that_nobody_will_clone_it():
    """A demo is worth some bytes and not unlimited ones. This is a ceiling with a reason rather
    than a number: a real console run with two instructions is about a third of a megabyte, and if
    a refresh ever produces several times that, something re-walked that should not have."""
    total = sum(p.stat().st_size for p in (DEMO / "conversations").rglob("*") if p.is_file())
    assert total < 900_000, (
        f"the fixture is {total:,} bytes. The 902 KB version was two redundant re-walks caused by "
        f"an agent that could not report itself finished — check for that before raising this.")
