"""The demo pages must be what the agents actually write.

A page committed once and never regenerated is a screenshot with an `.html` extension. It goes stale
the first time an agent changes and nothing notices — which is the same failure as a README stating
a number nobody re-measures, and this repository has shipped that twice.

So the pages are generated by `examples/demo/build.py`, and this regenerates them and compares.
"""
import importlib.util
import re
from pathlib import Path

import pytest

DEMO = Path(__file__).resolve().parent.parent / "examples" / "demo"
EXAMPLES = DEMO.parent


def _builder():
    spec = importlib.util.spec_from_file_location("demo_build", DEMO / "build.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


build = _builder()
GENERATED = build.generate()


@pytest.mark.parametrize("name", sorted(GENERATED))
def test_the_committed_page_is_the_one_the_agent_writes_today(name):
    on_disk = (DEMO / name)
    assert on_disk.exists(), f"{name} is missing; run `python3 examples/demo/build.py`"
    assert on_disk.read_text(encoding="utf-8") == GENERATED[name], (
        f"{name} is stale — the agent that builds it has changed. "
        f"Run `python3 examples/demo/build.py`.")


@pytest.mark.parametrize("demo", build.DEMOS, ids=lambda d: d["slug"])
def test_each_page_is_self_contained(demo):
    """A demo you cannot open by double-clicking is not much of a demo. The only thing any of them
    may reach for is a font."""
    page = GENERATED[f'{demo["slug"]}.html']
    assert 'href="styles.css"' not in page and "<script src=" not in page
    for reaching in ("fetch(", "XMLHttpRequest", "EventSource", "cdn.", "unpkg", "jsdelivr"):
        assert reaching not in page, f'{demo["slug"]}.html reaches for {reaching}'
    external = set(re.findall(r"https?://[^\s\"'<>)]+", page))
    allowed = {u for u in external if u.startswith("https://fonts.")}
    assert external == allowed, f"{demo['slug']}.html reaches off-machine: {external - allowed}"


@pytest.mark.parametrize("demo", build.DEMOS, ids=lambda d: d["slug"])
def test_the_index_links_every_demo_it_lists(demo):
    index = GENERATED["index.html"]
    assert f'href="{demo["slug"]}.html"' in index
    assert demo["title"] in index


def test_the_index_links_every_example_readme():
    index = GENERATED["index.html"]
    for example in ("minimal", "tide-spa", "weather-spa"):
        assert f"../{example}/README.md" in index, f"{example} is not linked from the demo index"


def test_every_example_has_its_own_readme():
    """Each example stands on its own. `examples/README.md` is the way in, not the documentation."""
    for example in ("minimal", "tide-spa", "weather-spa"):
        readme = EXAMPLES / example / "README.md"
        assert readme.exists(), f"{example} has no README of its own"
        assert readme.read_text(encoding="utf-8").lstrip().startswith("#")


def test_the_examples_index_links_each_one():
    index = (EXAMPLES / "README.md").read_text(encoding="utf-8")
    for example in ("minimal", "tide-spa", "weather-spa"):
        assert f"{example}/README.md" in index, f"{example} is not linked from examples/README.md"


def test_the_main_readme_links_the_examples_index_and_each_readme():
    main = (EXAMPLES.parent / "README.md").read_text(encoding="utf-8")
    assert "examples/README.md" in main
    for example in ("minimal", "tide-spa", "weather-spa"):
        assert f"examples/{example}/README.md" in main, f"the main README does not link {example}"


def test_every_relative_link_in_an_example_readme_resolves():
    """A README full of links that 404 is worse than one with none — it claims a structure that is
    not there. Anchors and external URLs are skipped; the point is the files."""
    broken = []
    for readme in sorted(EXAMPLES.rglob("README.md")):
        for target in re.findall(r"\]\(([^)]+)\)", readme.read_text(encoding="utf-8")):
            if target.startswith(("http://", "https://", "#", "mailto:")):
                continue
            path = (readme.parent / target.split("#", 1)[0]).resolve()
            if not path.exists():
                broken.append(f"{readme.relative_to(EXAMPLES.parent)} -> {target}")
    assert not broken, "dead links: " + ", ".join(broken)


def test_the_agents_the_demos_use_do_not_pick_the_next_module_by_missing_file(tmp_path):
    """The bug `weather-spa` scenario C exists to show. An agent with it cannot finish a rebuild, so
    `build.py` cannot generate a page from it — this asserts the shipped agents are the fixed kind
    by driving each one past the point where the broken kind loops."""
    import json
    import subprocess
    import sys

    for demo in build.DEMOS:
        work = tmp_path / demo["example"]
        work.mkdir(parents=True)
        (work / "agent.py").write_text(
            (EXAMPLES / demo["example"] / "agent.py").read_text(encoding="utf-8"),
            encoding="utf-8")
        order = json.dumps({"node_id": "engineer_build", "seat": None})
        answers = []
        for _ in range(6):
            done = subprocess.run([sys.executable, str(work / "agent.py")], input=order,
                                  capture_output=True, encoding="utf-8", errors="replace",
                                  cwd=str(work))
            answers.append(json.loads(done.stdout)["module"])
        assert answers[4] == "", (
            f'{demo["example"]}: a fifth build answered {answers[4]!r} instead of reporting '
            f"nothing to do — the frontier would never empty")
